### ISSUE TITLE
Accepting feedback on the Brigade Action Team framework

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/brigade-action-teams#2]
I invite your feedback on the [Brigade Action Team framework](https://docs.google.com/document/d/1X1S7Ibrj5rG1sW2P3EXLlLjAhPDfXCb0i5L6aX8BtXQ/edit#heading=h.9qn3kr18ft1j
). As you review it, I would remind you that it’s not a best practice to define tools that a community should use. However, in this instance, the framework was designed to leverage the tools the brigade network is already using in their work. 

You will see that we are standardizing with GitHub, Google Groups, Slack, Google Drive, and a shared Google calendar. Not all open source, but all being used commonly between brigades for their existing work. And to be honest, we’re not looking to have a debate on what tool we should use for what, new tools we use in the future will naturally be discussed as we evolve the framework.

**Comment by patwater** [comment]
Looks really solid. Would be curious to protocols for partnerships with external organizations. Thinking of use cases like the Louiseville-led Waze data collaboration: https://github.com/LouisvilleMetro/WazeCCPProcessor

**Comment by jhibbets** [comment]
I think the framework could still apply for groups that want to use it for
that purpose. I think one of the big advantages of for brigade is to have
everything on the Code for America infrastructure and organized in the same
way. BATs could easily bring in members to their teams from other partner
organizations.
Jason

**Comment by patwater** [comment]
Cool would be interested in exploring a brigade action team for [SQUID bike](https://medium.com/a-r-g-o/squid-bike-data-collection-how-to-a42dfd2d2454), particularly in CA with the billions of gas tax revenue coming down the pipeline for local road maintenance and transportation projects. We're gearing up to launch something in LA County and could be fun to do elsewhere. I'll dig into the protocol here and discussion submission with our team. 

For context in my day job I serve as project manager for the [California Data Collaborative](CaliforniaDataCollaborative.org) coalition of water utilities and somewhat serendipitously the utilities are organized into data action teams. Happy to share any practices there if y'all are curious though that's more government technical staff and academia rather than the nights and weekend crowd.
